// File generated by `flutterfire configure`.
// Do not edit this file manually.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.macOS:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArawklKE3yf6QsJ91SGJ-K1ikaRagy1Dk',
    appId: '1:513859324827:android:5add3ceca5cd92efc7af3e',
    messagingSenderId: '513859324827',
    projectId: 'nearme-bd95a',
    storageBucket: 'nearme-bd95a.firebasestorage.app',
    databaseURL: 'https://nearme-bd95a.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhuy8FgSxXUG40cW-9UIMKpgRPFmlbNDI',
    appId: '1:513859324827:ios:76a49a8ec58787a5c7af3e',
    messagingSenderId: '513859324827',
    projectId: 'nearme-bd95a',
    storageBucket: 'nearme-bd95a.firebasestorage.app',
    databaseURL: 'https://nearme-bd95a.firebaseio.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArawklKE3yf6QsJ91SGJ-K1ikaRagy1Dk',
    appId: '1:513859324827:web:e9c59e4a42f7b8d9c7af3e',
    authDomain: 'nearme-bd95a.firebaseapp.com',
    messagingSenderId: '513859324827',
    projectId: 'nearme-bd95a',
    storageBucket: 'nearme-bd95a.firebasestorage.app',
    databaseURL: 'https://nearme-bd95a.firebaseio.com',
  );
}
