import '../../data/models/country.dart';

const List<Country> kCountries = [
  Country(code: 'US', name: 'United States', flag: '🇺🇸', lang: 'en', currency: 'USD'),
  Country(code: 'GB', name: 'United Kingdom', flag: '🇬🇧', lang: 'en', currency: 'GBP'),
  Country(code: 'CA', name: 'Canada', flag: '🇨🇦', lang: 'en', currency: 'CAD'),
  Country(code: 'AU', name: 'Australia', flag: '🇦🇺', lang: 'en', currency: 'AUD'),
  Country(code: 'MX', name: 'Mexico', flag: '🇲🇽', lang: 'es', currency: 'MXN'),
  Country(code: 'ES', name: 'Spain', flag: '🇪🇸', lang: 'es', currency: 'EUR'),
  Country(code: 'AR', name: 'Argentina', flag: '🇦🇷', lang: 'es', currency: 'ARS'),
  Country(code: 'CO', name: 'Colombia', flag: '🇨🇴', lang: 'es', currency: 'COP'),
  Country(code: 'FR', name: 'France', flag: '🇫🇷', lang: 'fr', currency: 'EUR'),
  Country(code: 'BE', name: 'Belgium', flag: '🇧🇪', lang: 'fr', currency: 'EUR'),
  Country(code: 'CH', name: 'Switzerland', flag: '🇨🇭', lang: 'de', currency: 'CHF'),
  Country(code: 'DE', name: 'Germany', flag: '🇩🇪', lang: 'de', currency: 'EUR'),
  Country(code: 'AT', name: 'Austria', flag: '🇦🇹', lang: 'de', currency: 'EUR'),
  Country(code: 'BR', name: 'Brazil', flag: '🇧🇷', lang: 'pt', currency: 'BRL'),
  Country(code: 'PT', name: 'Portugal', flag: '🇵🇹', lang: 'pt', currency: 'EUR'),
  Country(code: 'JP', name: 'Japan', flag: '🇯🇵', lang: 'ja', currency: 'JPY'),
  Country(code: 'KR', name: 'South Korea', flag: '🇰🇷', lang: 'ko', currency: 'KRW'),
  Country(code: 'CN', name: 'China', flag: '🇨🇳', lang: 'zh', currency: 'CNY'),
  Country(code: 'TW', name: 'Taiwan', flag: '🇹🇼', lang: 'zh', currency: 'TWD'),
  Country(code: 'SG', name: 'Singapore', flag: '🇸🇬', lang: 'en', currency: 'SGD'),
  Country(code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦', lang: 'ar', currency: 'SAR'),
  Country(code: 'AE', name: 'UAE', flag: '🇦🇪', lang: 'ar', currency: 'AED'),
  Country(code: 'EG', name: 'Egypt', flag: '🇪🇬', lang: 'ar', currency: 'EGP'),
  Country(code: 'IN', name: 'India', flag: '🇮🇳', lang: 'hi', currency: 'INR'),
  Country(code: 'IT', name: 'Italy', flag: '🇮🇹', lang: 'it', currency: 'EUR'),
  Country(code: 'PH', name: 'Philippines', flag: '🇵🇭', lang: 'tl', currency: 'PHP'),
  Country(code: 'NL', name: 'Netherlands', flag: '🇳🇱', lang: 'en', currency: 'EUR'),
  Country(code: 'SE', name: 'Sweden', flag: '🇸🇪', lang: 'en', currency: 'SEK'),
  Country(code: 'NO', name: 'Norway', flag: '🇳🇴', lang: 'en', currency: 'NOK'),
  Country(code: 'DK', name: 'Denmark', flag: '🇩🇰', lang: 'en', currency: 'DKK'),
  Country(code: 'NZ', name: 'New Zealand', flag: '🇳🇿', lang: 'en', currency: 'NZD'),
  Country(code: 'ZA', name: 'South Africa', flag: '🇿🇦', lang: 'en', currency: 'ZAR'),
  Country(code: 'NG', name: 'Nigeria', flag: '🇳🇬', lang: 'en', currency: 'NGN'),
  Country(code: 'KE', name: 'Kenya', flag: '🇰🇪', lang: 'en', currency: 'KES'),
  Country(code: 'MY', name: 'Malaysia', flag: '🇲🇾', lang: 'en', currency: 'MYR'),
  Country(code: 'TH', name: 'Thailand', flag: '🇹🇭', lang: 'en', currency: 'THB'),
  Country(code: 'ID', name: 'Indonesia', flag: '🇮🇩', lang: 'en', currency: 'IDR'),
  Country(code: 'PL', name: 'Poland', flag: '🇵🇱', lang: 'en', currency: 'PLN'),
  Country(code: 'CZ', name: 'Czech Republic', flag: '🇨🇿', lang: 'en', currency: 'CZK'),
  Country(code: 'GR', name: 'Greece', flag: '🇬🇷', lang: 'en', currency: 'EUR'),
  Country(code: 'PK', name: 'Pakistan', flag: '🇵🇰', lang: 'ar', currency: 'PKR'),
  Country(code: 'BD', name: 'Bangladesh', flag: '🇧🇩', lang: 'en', currency: 'BDT'),
];
