import '../../data/models/profile.dart';

const List<Profile> kSampleProfiles = [
  Profile(
    name: 'Sofia',
    age: 26,
    emoji: '🌺',
    hood: 'Montrose',
    country: 'US',
    distanceKm: 0.6,
    bio: "Always at Catalina Coffee on Sunday mornings. Looking for someone to explore the neighborhood with ☕",
    tags: ['☕ Coffee', '🎨 Art', '🐕 Dogs'],
    badge: '🏠 2 shared spots',
    gender: 'Women',
    goal: 'Long-term',
    verified: true,
    online: true,
    sharedSpots: true,
  ),
  Profile(
    name: 'Alex',
    age: 29,
    emoji: '🏄',
    hood: 'Montrose',
    country: 'US',
    distanceKm: 1.3,
    bio: 'Engineer who loves the farmers market and hidden local gems 🌿',
    tags: ['🏄 Outdoors', '💻 Tech', '🌿 Plants'],
    badge: '🏠 1 shared spot',
    gender: 'Men',
    goal: 'Casual',
    verified: true,
    online: true,
    sharedSpots: false,
  ),
  Profile(
    name: 'Jamie',
    age: 27,
    emoji: '🌿',
    hood: 'Heights',
    country: 'US',
    distanceKm: 1.8,
    bio: "Plant lover, yoga instructor, food explorer. Let's discover the neighborhood together.",
    tags: ['🧘 Yoga', '🌮 Foodie', '🎨 Art'],
    badge: '⭐ New to area',
    gender: 'Non-binary',
    goal: 'Friendship',
    verified: true,
    online: false,
    sharedSpots: false,
  ),
  Profile(
    name: 'Riley',
    age: 31,
    emoji: '🎸',
    hood: 'Montrose',
    country: 'US',
    distanceKm: 1.5,
    bio: 'Musician and coffee snob. Live music venue regular 🎶',
    tags: ['🎶 Music', '☕ Coffee', '🎸 Guitar'],
    badge: '🏠 3 shared spots',
    gender: 'Women',
    goal: 'Long-term',
    verified: false,
    online: false,
    sharedSpots: true,
  ),
  Profile(
    name: 'Morgan',
    age: 24,
    emoji: '📸',
    hood: 'Midtown',
    country: 'US',
    distanceKm: 3.0,
    bio: 'Photographer documenting street art. Always looking for new spots.',
    tags: ['📸 Photography', '🎨 Art', '🚴 Cycling'],
    badge: '🏠 1 shared spot',
    gender: 'Non-binary',
    goal: 'Casual',
    verified: true,
    online: true,
    sharedSpots: false,
  ),
  Profile(
    name: 'Casey',
    age: 33,
    emoji: '🌮',
    hood: 'Montrose',
    country: 'US',
    distanceKm: 0.9,
    bio: 'Food enthusiast and weekend hiker. Big fan of local culture.',
    tags: ['🌮 Foodie', '🥾 Hiking', '🐕 Dogs'],
    badge: '🏠 2 shared spots',
    gender: 'Men',
    goal: 'Long-term',
    verified: true,
    online: false,
    sharedSpots: true,
  ),
];
